import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <div className="mx-auto flex min-h-[85vh] flex-col items-center justify-center p-4">
                    <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
                        SeatGeek Design
                    </h1>
                    <p className="text-2xl text-gray-900">Live event ticketing sucks. We're on a mission to change that.</p>
                </div>
                <div className="bg-gray-900 mx-auto flex min-h-[85vh] flex-col items-center justify-center p-4">
                    <h1 className="text-5xl font-extrabold leading-normal text-white md:text-[5rem]">
                        SeatGeek Design
                    </h1>
                    <p className="text-2xl text-gray-400">We handle the tickets. So fans can fan.</p>
                </div>
            </main>
        </>
    );
};

export default Home;

type TechnologyCardProps = {
    name: string;
    description: string;
    documentation: string;
};

const TechnologyCard = ({
    name,
    description,
    documentation,
}: TechnologyCardProps) => {
    return (
        <section className="flex flex-col justify-center rounded border-2 border-gray-500 p-6 shadow-xl duration-500 motion-safe:hover:scale-105">
            <h2 className="text-lg text-gray-700">{name}</h2>
            <p className="text-sm text-gray-600">{description}</p>
            <a
                className="m-auto mt-3 w-fit text-sm text-violet-500 underline decoration-dotted underline-offset-2"
                href={documentation}
                target="_blank"
                rel="noreferrer"
            >
                Documentation
            </a>
        </section>
    );
};
